### ISSUE TITLE
Theming

### ISSUE THREAD

**Issue by therealsharath** [GTBitsOfGood/bog-component-library#119]
### Acceptance Criteria
- Add theming to the repo and rewrite existing components

#### Tasks
- [ ] Re-write Alert component
- [ ] Re-write Button component
- [ ] Re-write Checkbox component
- [ ] Re-write Dropdown component
- [ ] Re-write Input component
- [ ] Re-write RadioButton component
- [ ] Re-write Switch component
- [ ] Add theme
- [ ] Add constants
- [ ] Add utils

### User Story
- We need theming

### Resources and PoC
- EM - @therealsharath
